name: 'Set environment variable'
  uses: tw3lveparsecs/github-actions-set-variables@v0.1
description: 'Configures environment variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/*
runs:
  using: "composite"
  steps:
    - run: |
        sed "" ${{ inputs.myvars.env }} >> $GITHUB_ENV
      shell: bash
