name: Docker Image CI


on:
  #schedule:
    #- cron: '27 15 * * *'
  push:
    #branches: [ main ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  #pull_request:
    branches: [ main ]


jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/myvars.env

  build:
    runs-on: ubuntu-latest
    steps:
    - name: display vars
      run: |
        echo $GITHUB_ENV.MYVAR1
        echo $GITHUB_ENV.MYVAR2       
      
