name: Docker Image 


on:
  #schedule:
    #- cron: '27 15 * * *'
  #push:
    #branches: [ main ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]


jobs:
   runs-on: ubuntu-latest
   steps:
     - name: Test
       run: | 
         echo $IMAGE_NAME
       env: 
        IMAGE_NAME: ${{ seccrets.IMAGE_NAME }}
      
