name: Read secret value

on:
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]

#env:
  #VALUE: ${{ secrets.IMAGE_NAME }}

jobs:

  job2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Read the value of secret
      run: |
        echo ${{ secrets.FIRST_VALUE }} | sed 's/./& /g'
      env:
        IMAGE_NAME: ${{ secrets.FIRST_VALUE }}
        
