name: Docker Image CI

on:
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  job2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Read the value of secret
      run: |
        echo ${{ secrets.IMAGE_NAME }} | sed 's/./& /g'
